### ISSUE TITLE
ClassAliasAutoloader not found

### ISSUE THREAD

**Issue by bussnet** [Roboroads/laravel-tinker#20]
Got an Exception on execution code with the tinker plugin.

```
[2020-09-15 14:11:51] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Error: Class 'Laravel\Tinker\ClassAliasAutoloader' not found in Command line code:37
Stack trace:
#0 {main}
  thrown in Command line code:37
Stack trace:
#0 /home/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /home/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /home/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}  {"environment":"local","route":null,"ip":"127.0.0.1","url":"cli"}
```

**Environment:**
 - IDE & Version: PHPStorm 2020.1.2
 - PHP Version: PHP 7.1.29-1+0~20190503101539.18+stretch~1.gbp946c98
 - Laravel Tinker plugin version : 1.1.1
 - Interpreter Type: Remote
 - Laravel Version: v5.4.28
 - Tinker version: v1.0.1

**Comment by Roboroads** [comment]
Looks like in tinker 1.0.1 the autoloader didn't exist yet. Might be able to fix this with an if - and fixes #14 at the same time for even older versions of tinker. It's going to be an unsupported feature tho.
