### ISSUE TITLE
[Bug]: output gets printed twice

### ISSUE THREAD

**Issue by michabbb** [Roboroads/laravel-tinker#225]
### Short bug description

the output always gets printed twice

### Extended bug description

it looks like it has something to do with the latest changes to version 2.5.0

### How to reproduce?

```php
function test()
{
    return 'test';
}
return test();
```

### Expected behavior

see output only once

### Screenshots

![image](https://user-images.githubusercontent.com/3524595/207989522-321c1f11-a4e2-4a05-aedd-5e7d9639af47.png)

### IDE & Version

phpstorm 2022.3

### PHP Version

8.1

### OS and version

Linux

### Laravel Tinker plugin version

2.5.0

### Interpreter type

{"label"=>"Docker (NOT compose)"}

### Laravel Version

9

### Tinker version

2.5.0

### Psysh version

v0.11.9

**Comment by Roboroads** [comment]
I tried to reproduce in multiple ways, but "Using a docker interpreter on unspecified Linux distribution" led me to not being able to reproduce.

![image](https://user-images.githubusercontent.com/4398301/207996212-ce0a7ca0-e46c-4201-b922-60d99bc71d28.png)

Using the docker image php:8.1-cli

**Comment by michabbb** [comment]
i tested with 2.5.1, same. and i can definitely say, before 2.5.0 I didn´t have that issue... strange 🤔

**Comment by michabbb** [comment]
here´s my php interpreter setup, maybe you see something strange:

![image](https://user-images.githubusercontent.com/3524595/207996693-b79d366d-467b-445b-a48c-190d355c2cf6.png)

**Comment by Roboroads** [comment]
Nothing strange there. Let me try with just php:8.1 - i used -cli

**Comment by michabbb** [comment]
it´s a custom image, but there is nothing special in my image, and as said: before I used the same image, without seeing the output twice...

**Comment by michabbb** [comment]
is there a way to download an older version of tinker so I can test if that is related to my env ?

**Comment by Roboroads** [comment]
I believe you, no worries, I just _have_ to reproduce the issue to fix it :(

**Comment by Roboroads** [comment]
> is there a way to download an older version of tinker so I can test if that is related to my env ?

Def. just download the zip from version you want to install from the [Releases page](https://github.com/Roboroads/laravel-tinker/releases)

**Comment by michabbb** [comment]
okay will do 👍

**Comment by Roboroads** [comment]
![image](https://user-images.githubusercontent.com/4398301/207997222-e7bab915-33c5-466d-b323-4d93e11f404a.png)

**Comment by michabbb** [comment]
![image](https://user-images.githubusercontent.com/3524595/207997626-b3290f54-e0c4-4712-aec4-b5330098ee0e.png)

here´s my output with 2.4.0 🙈

**Comment by Roboroads** [comment]
[Laravel Tinker-2.5.1+1.zip](https://github.com/Roboroads/laravel-tinker/files/10241937/Laravel.Tinker-2.5.1%2B1.zip)
How much outputs does this build give you?

**Comment by michabbb** [comment]
![image](https://user-images.githubusercontent.com/3524595/208001608-5dcefa91-77b1-4575-ac1a-b32f5811fc54.png)

**Comment by Roboroads** [comment]
Alright, so it's not what i suspected. That's good :)

**Comment by Roboroads** [comment]
What about a fresh laravel install? Do you have the problem there?

**Comment by michabbb** [comment]
puh.... i need to test that.... but later.... i need to 😴 🛏️ now 😪 😏

**Comment by Roboroads** [comment]
Same, haha, but I got you another build to test something. This will tell me if it's in the plugins kotlin code orsomewhere in PHP.

[Laravel Tinker-2.5.1+1.zip](https://github.com/Roboroads/laravel-tinker/files/10241980/Laravel.Tinker-2.5.1%2B1.zip)

I added some <%> to the output. the amount of them will tell me a lot.

**Comment by michabbb** [comment]
sorry, i am unable to test because of:

```txt
java.lang.NullPointerException
	at nl.deschepers.laraveltinker.toolwindow.TinkerOutputToolwindow.<init>(TinkerOutputToolwindow.kt:44)
	at nl.deschepers.laraveltinker.toolwindow.TinkerOutputToolWindowFactory.createToolWindowContent(TinkerOutputToolWindowFactory.kt:25)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:543)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:522)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1009)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:946)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:662)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.kt:622)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.activateToolWindow(BackendServerToolWindowManager.kt:189)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$default(ToolWindowManagerImpl.kt:616)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.activate(ToolWindowImpl.kt:253)
	at com.intellij.openapi.wm.ToolWindow.activate(ToolWindow.java:43)
	at nl.deschepers.laraveltinker.util.PhpArtisanTinkerUtil.run(PhpArtisanTinkerUtil.kt:125)
	at nl.deschepers.laraveltinker.util.TinkerConsoleUtil.runTinkerWithFile(TinkerConsoleUtil.kt:32)
	at nl.deschepers.laraveltinker.action.RunConsoleAction.actionPerformed(RunConsoleAction.kt:32)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:703)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by Roboroads** [comment]
Yea this happens to me too when developing. You can deinstall, reboot PHPStorm, install, should fix it. I'm still trying to work this one out

**Comment by michabbb** [comment]
i did, but i get the same exception, sorry 😕

**Comment by michabbb** [comment]
in case it helps, i can offer you a call with screen share...  😏

**Comment by christoferd** [comment]
What do you get if you run > composer update
What do you get if you run > php artisan
Any errors?
I'm not sure if this tinker plugin uses same code as artisan or not. But doesn't hurt to see if your base code has issues.

**Comment by Roboroads** [comment]
> i did, but i get the same exception, sorry confused

I asked jetbrains about this.

> in case it helps, i can offer you a call with screen share... smirk

If you get the toolwindow back to working we can do that, my discord is Roboroads#1337

**Comment by michabbb** [comment]
@Roboroads invite sent 😏 (goddy....)

**Comment by Roboroads** [comment]
We figured out it's not the plugin causing this
