### ISSUE TITLE
[Bug]: java.lang.IllegalStateException: This method is forbidden on EDT because it does not pump the event queue. Switch to a BGT, or use com.intellij.openapi.progress.TasksKt.runWithModalProgressBlocking. 

### ISSUE THREAD

**Issue by michabbb** [Roboroads/laravel-tinker#388]
### Short bug description

java.lang.IllegalStateException: This method is forbidden on EDT because it does not pump the event queue. Switch to a BGT, or use com.intellij.openapi.progress.TasksKt.runWithModalProgressBlocking. 

### Extended bug description

java.lang.IllegalStateException: This method is forbidden on EDT because it does not pump the event queue. Switch to a BGT, or use com.intellij.openapi.progress.TasksKt.runWithModalProgressBlocking. 
	at com.intellij.openapi.progress.CoroutinesKt.assertBackgroundThreadOrWriteAction(coroutines.kt:473)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:139)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingMaybeCancellable(coroutines.kt:176)
	at com.intellij.docker.utils.RemoteDockerRuntimeUtil.executeAgentTask$lambda$5(RemoteDockerRuntimeUtil.kt:92)
	at com.intellij.docker.utils.RemoteDockerRuntimeUtil.executeAgentTask(RemoteDockerRuntimeUtil.kt:110)
	at com.intellij.docker.utils.RemoteDockerRuntimeUtil.executeAgentTask(RemoteDockerRuntimeUtil.kt:90)
	at com.intellij.docker.remoteRunRuntime.RemoteDockerApplicationRuntime.executeAgentTask(RemoteDockerApplicationRuntime.java:170)
	at com.intellij.docker.remoteRunRuntime.RemoteDockerApplicationRuntime.create(RemoteDockerApplicationRuntime.java:127)
	at com.intellij.docker.remoteRunRuntime.RemoteDockerApplicationRuntime.create(RemoteDockerApplicationRuntime.java:62)
	at com.intellij.docker.remoteRunRuntime.RemoteDockerApplicationRuntime.createWithImageInitialization(RemoteDockerApplicationRuntime.java:320)
	at com.intellij.docker.remoteRunRuntime.RemoteDockerApplicationRuntime.createWithPullImage(RemoteDockerApplicationRuntime.java:336)
	at com.intellij.docker.remote.run.runtime.DockerExecProcess$Factory.startProcessWithRemove(DockerExecProcess.kt:185)
	at com.jetbrains.php.remote.docker.PhpDockerRemoteProcessRunner.startRemoteProcess(PhpDockerRemoteProcessRunner.java:204)
	at com.jetbrains.php.remote.docker.PhpDockerRemoteProcessRunner.getRemoteProcess(PhpDockerRemoteProcessRunner.java:129)
	at com.jetbrains.php.remote.PhpRemoteInterpreterManagerImpl.getRemoteProcessHandler(PhpRemoteInterpreterManagerImpl.java:176)
	at com.jetbrains.php.run.PhpRunConfiguration.createProcessHandler(PhpRunConfiguration.java:118)
	at com.jetbrains.php.run.PhpRunConfiguration.createProcessHandler(PhpRunConfiguration.java:88)
	at nl.deschepers.laraveltinker.util.PhpArtisanTinkerUtil.run(PhpArtisanTinkerUtil.kt:101)
	at nl.deschepers.laraveltinker.util.TinkerConsoleUtil.runTinkerWithFile(TinkerConsoleUtil.kt:32)
	at nl.deschepers.laraveltinker.action.RunConsoleAction.actionPerformed(RunConsoleAction.kt:33)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:374)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:32)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$actionProcessor$1.performAction(IdeKeyEventDispatcher.kt:499)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$8$lambda$7(IdeKeyEventDispatcher.kt:850)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:98)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$8(IdeKeyEventDispatcher.kt:850)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1173)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.kt:396)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner(IdeKeyEventDispatcher.kt:848)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.access$doPerformActionInner(IdeKeyEventDispatcher.kt:1)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:577)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:512)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.kt:451)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.kt:444)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.kt:306)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:606)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$22(IdeEventQueue.kt:565)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

### Your project is not the problem

- [X] I tried using a fresh laravel install - I'm fairly certain it has nothing to do with my project.

### How to reproduce?

just run a console

### Expected behavior

no exception

### IDE & Version

PhpStorm 2024.3.1.1

### PHP Version

8.3.7

### OS and version

ubuntu

### Laravel Tinker plugin version

2.7.3

### Interpreter type

Docker (NOT compose)

### Laravel Version

11.30

### Tinker version

2.10.0

### Psysh version

0.12.7

**Comment by nmolham-godaddy** [comment]
I am having the error recently as well

**Comment by michabbb** [comment]
oh this is old 😢 but the same as #392
